"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import AuthProvider from "./AuthProvider";
import Navbar from "./components/Navbar";
import { useEffect } from "react";
import { useStockStore } from "@/store/useStockStore";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const connectSocket = useStockStore((s) => s.connectSocket);

  useEffect(() => {
    connectSocket();
  }, []);

  return (
    <html
      lang="en"
      // className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <Navbar />
          {children}

          <Toaster
            position="top-center"
            toastOptions={{
              duration: 2000,
            }}
          />
        </AuthProvider>
      </body>
    </html>
  );
}
